
[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨â‡¡${count}'
behind = 'ğŸ˜°â‡£${count}'
diverged = 'ğŸ˜µâ‡•â‡¡${ahead_count}â‡£${behind_count}'
up_to_date = 'âœ“'
untracked = 'ğŸ¤· ${count}'
stashed = 'ğŸ“¦ ${count}'
modified = '${count} ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘… ${count}'
deleted = 'ğŸ—‘ ${count}'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

[kubernetes]
format = 'on [â›µ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false

[terraform]
format = '[ğŸ’  $version$workspace]($style) '
detect_extensions = ['tf', 'tfplan', 'tfstate']
disabled = false
